language: go

sudo: false

install:
  # dependencies - TODO use godep or etc
  - go get github.com/jhoonb/archivex
  - go get github.com/stretchr/testify/assert

script:
  - ./ci/unittest.sh
  - go build -v

notification:
  email: false
